// popup-container/src/components/popup-container/popup-container.jsx
import React from "react";
import styles from "./popup-container.module.css";
import CloseIcon from "../../assets/icons/closeicon.svg";
export const PopupContainer = ({ open, setClose, children }) => {
  return (
    <div
      className={`${styles.popupContainer} ${
        open ? styles.open : styles.close
      }`}
    >
      <button
        onClick={() => setClose()}
        type="button"
        className={styles.closeButton}
      >
        <img src={CloseIcon} alt="" height="15px" width="15px" />
      </button>
      <div className={styles.content}>{children}</div>
    </div>
  );
};

// ng-popup-container/src/app/components/popup-container/popup-container.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-popup-container',
  templateUrl: './popup-container.component.html',
  styleUrls: ['./popup-container.component.scss'],
})
export class PopupContainerComponent implements OnInit {
  open = false;
  constructor() {}

  ngOnInit(): void {}
  setOpen() {
    this.open = true;
  }
  setClose() {
    this.open = false;
  }
  toggle() {
    this.open = !this.open;
  }
}

<div class="popup-container" [ngClass]="open ? 'open' : 'close'">
  <button class="close-button" type="button">
    <img
      src="../../../assets/icons/closeicon.svg"
      alt=""
      width="15px"
      height="15px"
      (click)="setClose()"
    />
  </button>
  <div class="content">
    <ng-content></ng-content>
  </div>
</div>
