// ng-popup-container/src/app/components/large-content/large-content.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-large-content',
  templateUrl: './large-content.component.html',
  styleUrls: ['./large-content.component.scss']
})
export class LargeContentComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<h1>This is some large content with some lorem ipsum</h1>
<hr />
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam earum quidem
  accusantium non sed quisquam suscipit dolorem, id quo quod provident labore
  aut illum magnam itaque fugit reprehenderit, optio pariatur?
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. In mollitia qui
  soluta vero animi eius architecto voluptatum adipisci aliquid culpa! Molestiae
  inventore aliquam ut, perspiciatis a laboriosam ab quidem modi. Lorem ipsum
  dolor sit amet consectetur adipisicing elit. Numquam id, quis, repellat velit
  ipsum expedita sint ex ea amet sit excepturi provident eaque eum officia,
  sequi autem quos maxime optio. Lorem ipsum, dolor sit amet consectetur
  adipisicing elit. Repellendus, mollitia nobis? Libero, possimus aspernatur,
  distinctio sit inventore ut facere dolorem ex assumenda quibusdam non aperiam
  porro iste odit amet? Aliquid. Lorem ipsum dolor sit amet consectetur
  adipisicing elit. Inventore porro vitae assumenda, pariatur nemo maxime dolor
  aliquid recusandae labore at unde modi fugiat delectus cum quaerat itaque
  dolore, repudiandae fuga. Lorem ipsum dolor sit amet consectetur adipisicing
  elit. Maxime earum, deleniti corrupti, itaque, quis fugiat temporibus dicta
  aut tempore unde quos dolorem? Corrupti mollitia tenetur culpa assumenda
  repellendus veritatis hic!
</p>

<img src="../../../assets/images/largeImage.JPG" alt="" width="100%" />

// popup-container/src/components/large-content/large-content.jsx
import React from "react";
import LargeImage from "../../assets/images/largeImage.JPG";
export const LargeContent = () => (
  <>
    <h1>Here is some lorem ipsum</h1>
    <hr />
    <p>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem earum ea
      magni unde, cupiditate a laborum consequatur? Facere magni libero rerum
      fuga assumenda, quae sapiente illum reprehenderit iste quam blanditiis.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia saepe beatae
      dicta ipsam perferendis suscipit voluptas quae cum corrupti, totam
      distinctio voluptatum earum odit iure sint non animi corporis optio? Lorem
      ipsum dolor sit amet consectetur adipisicing elit. Natus delectus ad
      consequatur deserunt rem voluptatem, officia nemo alias rerum beatae
      architecto voluptas omnis aspernatur ex repudiandae deleniti fugiat qui
      nam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem
      suscipit nisi officiis eos esse neque reprehenderit. Quasi, est optio
      fugiat enim dolor porro totam. Voluptates vel quae maxime sit obcaecati.
    </p>
    <img src={LargeImage} alt="" width="100%" />
  </>
);
